#!/bin/bash
sudo useradd --no-create-home --shell /bin/false prometheus
sudo mkdir /etc/prometheus
sudo mkdir /var/lib/prometheus
sudo chown -R prometheus:prometheus /var/lib/prometheus
wget https://github.com/prometheus/prometheus/releases/download/v2.45.3/prometheus-2.45.3.linux-amd64.tar.gz -P /tmp
cd /tmp
tar xvf /tmp/prometheus-2.45.3.linux-amd64.tar.gz
sudo cp /tmp/prometheus-2.45.3.linux-amd64/prometheus /usr/local/bin/
sudo cp /tmp/prometheus-2.45.3.linux-amd64/promtool /usr/local/bin/
sudo chown prometheus:prometheus /usr/local/bin/prometheus
sudo chown prometheus:prometheus /usr/local/bin/promtool
sudo cp -r /tmp/prometheus-2.45.3.linux-amd64/consoles /etc/prometheus
sudo cp -r /tmp/prometheus-2.45.3.linux-amd64/console_libraries /etc/prometheus
sudo chown -R prometheus:prometheus  /etc/prometheus/consoles
sudo chown -R prometheus:prometheus  /etc/prometheus/console_libraries
PUBLIC_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-hostname)s
sudo tee /etc/prometheus/prometheus.yml <<EOF
global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus_private'
        scrape_interval: 5s
        static_configs:
        - targets: ['localhost:9090']
  - job_name: 'prometheus_public'
        scrape_interval: 5s
        static_configs:
        - targets: [$PUBLIC_IP:9090']
EOF
sudo tee /etc/systemd/system/prometheus.service <<EOF
[Unit]
Description=Prometheus
Wants=network-online.target
After=network-online.target

[Service]
User=prometheus
Group=prometheus
Type=simple
ExecStart=/usr/local/bin/prometheus \
--config.file=/etc/prometheus/prometheus.yml \
--storage.tsdb.path=/var/lib/prometheus/ \
--web.console.templates=/etc/prometheus/consoles \
--web.console.libraries=/etc/prometheus/console_libraries \
--web.enable-lifecycle \
--web.enable-admin-api \
--log.level=info

[Install]
WantedBy=multi-user.target
EOF
sudo systemctl daemon-reload
sudo systemctl start prometheus
sudo systemctl enable prometheus
sudo useradd --no-create-home --shell /bin/false node_exporter
wget https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz -P /tmp
cd /tmp
tar xvf node_exporter-1.7.0.linux-amd64.tar.gz
sudo cp /tmp/node_exporter-1.7.0.linux-amd64/node_exporter /usr/local/bin/
sudo chown node_exporter:node_exporter /usr/local/bin/node_exporter
sudo tee /lib/systemd/system/node_exporter.service <<EOF
[Unit]
Description=Node Exporter
After=network.target

[Service]
User=node_exporter
Group=node_exporter
Type=simple
ExecStart=/usr/local/bin/node_exporter

[Install]
WantedBy=multi-user.target
EOF
sudo systemctl daemon-reload
sudo systemctl start node_exporter
sudo systemctl enable node_exporter
sudo systemctl status node_exporter