global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus_private"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "prometheus_public"
    scrape_interval: 5s
    static_configs:
      - targets: ["ec2-18-60-212-140.ap-south-2.compute.amazonaws.com:9090"]
  - job_name: "prometheus_node_exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["ec2-18-60-216-32.ap-south-2.compute.amazonaws.com:9100"]
  - job_name: "prometheus_webservers"
    scrape_interval: 5s
    static_configs:
      - targets: ["<machine-1-ip>:9100", "<machine-2-ip>:9100"]
